### ISSUE TITLE
How to enable all gpus? 

### ISSUE THREAD

**Issue by cndu234** [VinAIResearch/3D-UCaps#5]
Even when i choose` --gpus = 0,1`  and `--gpus=2` , it is considering only one GPU for training. I have two gpus and wanted to use them both. Please let me know how to enable my both GPUs

**Comment by hoangtan96dl** [comment]
Can you show me the log of your run? Pytorch lightning will print out which devices you are using in that run. You are using the right argument so I do not know what causes your problem.

**Comment by cndu234** [comment]
`Global seed set to 0
DataModule property `train_transforms` was deprecated in v1.5 and will be removed in v1.7.
DataModule property `val_transforms` was deprecated in v1.5 and will be removed in v1.7.
Trainer argument `terminate_on_nan` was deprecated in v1.5 and will be removed in 1.7. Please use `Trainer(detect_anomaly=True)` instead.
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
55
14
DataModule property `train_transforms` was deprecated in v1.5 and will be removed in v1.7.
DataModule property `val_transforms` was deprecated in v1.5 and will be removed in v1.7.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
The `LightningModule.loaded_optimizer_states_dict` property is deprecated in v1.4 and will be removed in v1.6.
Global seed set to 0
Global seed set to 0
initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/2
initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/2
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 2 processes
----------------------------------------------------------------------------------------------------


  | Name                 | Type              | Params | In sizes               | Out sizes             
-------------------------------------------------------------------------------------------------------------
0 | classification_loss1 | MarginLoss        | 0      | ?                      | ?                     
1 | classification_loss2 | DiceCELoss        | 0      | ?                      | ?                     
2 | reconstruction_loss  | MSELoss           | 0      | ?                      | ?                     
3 | feature_extractor    | Sequential        | 322 K  | [1, 1, 32, 32, 32]     | [1, 64, 32, 32, 32]   
4 | primary_caps         | ConvSlimCapsule3D | 110 K  | [1, 1, 64, 32, 32, 32] | [1, 16, 4, 32, 32, 32]
5 | encoder_conv_caps    | ModuleList        | 347 K  | ?                      | ?                     
6 | decoder_conv         | ModuleList        | 2.2 M  | ?                      | ?                     
7 | reconstruct_branch   | Sequential        | 16.7 K | ?                      | ?                     
-------------------------------------------------------------------------------------------------------------
3.0 M     Trainable params
0         Non-trainable params
3.0 M     Total params
11.972    Total estimated model params size (MB)
num_workers>0, persistent_workers=False, and strategy=ddp_spawn may result in data loading bottlenecks. Consider setting persistent_workers=True (this is a limitation of Python .spawn() and PyTorch)
Epoch 0:   0%|                                           | 0/28 [00:00<?, ?it/s]Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 1. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
Traceback (most recent call last):
  File "train.py", line 133, in <module>
    trainer.fit(net, datamodule=data_module)
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in fit
    self._call_and_handle_interrupt(
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 682, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 772, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1195, in _run
    self._dispatch()
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1274, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp_spawn.py", line 173, in start_training
    self.spawn(self.new_process, trainer, self.mp_queue, return_result=False)
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp_spawn.py", line 201, in spawn
    mp.spawn(self._wrapped_function, args=(function, args, kwargs, return_queue), nprocs=self.num_processes)
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp_spawn.py", line 208, in _wrapped_function
    result = function(*args, **kwargs)
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp_spawn.py", line 236, in new_process
    results = trainer.run_stage()
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1284, in run_stage
    return self._run_train()
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1314, in _run_train
    self.fit_loop.run()
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 234, in advance
    self.epoch_loop.run(data_fetcher)
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 195, in advance
    batch_output = self.batch_loop.run(batch, batch_idx)
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(split_batch, optimizers, batch_idx)
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 215, in advance
    result = self._run_optimization(
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 266, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, batch_idx, closure)
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 378, in _optimizer_step
    lightning_module.optimizer_step(
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py", line 1664, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 164, in step
    trainer.accelerator.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 336, in optimizer_step
    self.precision_plugin.optimizer_step(model, optimizer, opt_idx, closure, **kwargs)
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 163, in optimizer_step
    optimizer.step(closure=closure, **kwargs)
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/torch/optim/adam.py", line 66, in step
    loss = closure()
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 148, in _wrap_closure
    closure_result = closure()
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 160, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 142, in closure
    step_output = self._step_fn()
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 435, in _training_step
    training_step_output = self.trainer.accelerator.training_step(step_kwargs)
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 216, in training_step
    return self.training_type_plugin.training_step(*step_kwargs.values())
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp_spawn.py", line 382, in training_step
    return self.model(*args, **kwargs)
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 619, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/pytorch_lightning/overrides/base.py", line 81, in forward
    output = self.module.training_step(*inputs, **kwargs)
  File "/mnt/DATA/sindhura/3D-UCaps/module/ucaps.py", line 217, in training_step
    conv_cap_2_1 = self.encoder_conv_caps[1](x)
  File "/mnt/DATA/anaconda3/envs/UCaps/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/DATA/sindhura/3D-UCaps/layers.py", line 479, in forward
    return _update_routing(votes, self.biases, self.num_routing)
  File "/mnt/DATA/sindhura/3D-UCaps/layers.py", line 54, in _update_routing
    preactivate = torch.sum(votes * route, dim=1) + biases[None, ...]
RuntimeError: CUDA out of memory. Tried to allocate 6.25 GiB (GPU 0; 47.46 GiB total capacity; 40.70 GiB already allocated; 4.47 GiB free; 41.98 GiB reserved in total by PyTorch)

`

**Comment by cndu234** [comment]
Thank you ..its working as you said. There were some issues at my end
